name: Assign Project Fields Based on Labels

on:
  issues:
    types: [labeled, unlabeled, opened]

jobs:
  update-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update project fields based on labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          
          LABELS=$(gh issue view $ISSUE_NUMBER --repo $REPO --json labels --jq '.labels[].name')
          echo $LABELS
          ISSUE_ID=$(gh issue view $ISSUE_NUMBER --json id --repo ansermino/gha-labels-test --jq '.id')
          echo $ISSUE_ID
          
          # Define your label to project field mappings
          if echo "$LABELS" | grep -q "p0"; then
            gh api graphql -f query='
              mutation {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: "PVT_kwHOANgikM4Alq7A", 
                    itemId: $ISSUE_ID, 
                    fieldId: "PVTSSF_lAHOANgikM4Alq7AzgdsEGE", 
                    value: {singleSelectOptionId: "7942a8e8"}}
                ) {
                  projectV2Item {
                    id
                  }
                }
              }'
          fi
